name: Build & Deploy (Railway)

on:
  push:
    paths: ["backend/**"]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: railwayapp/railway-deploy-action@v2
        with:
          railwayToken: ${{ secrets.RAILWAY_API_TOKEN }}
          projectId:    ${{ secrets.RAILWAY_PROJECT_ID }}
          serviceName:  api
          cwd: backend